### ISSUE TITLE
Create the main page for the Admin Panel

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-ecommerce#13]
@kjcioffi I wanted to break down #2 issue down further so that it is more easily addressed:

- [ ] create a view in views.py that returns a page store_admin.html
- - [ ] This view should have the loginrequired mixin
- [ ] on this template render a menu as desired (e.g sidebar or vertical bar menu with the required pages, products, orders etc)

**Comment by kjcioffi** [comment]
Perfect, this certainly helps to clarify things. So an ability to navigate to Products, Orders, and Stores on one page?

**Comment by ryaustin** [comment]
Yes!!

**Comment by ryaustin** [comment]
Hey Kevin, it's really just a preference - no wrong answer. 

What CSS does give us though is the ability to fill the space with the rendered menu whether there are 2 or 4 options horizontally / vertically. In an ideal design, a user most likely wouldn't know if an option is missing as what they have access to should render perfectly. 

So this is more cosmetic if I am understanding your question correctly.

**Comment by kjcioffi** [comment]
I will use the navigation bar on the site to handle this work. Regarding work on #3, I will create a drop-down that enables store owners to navigate and use admin operations as they see fit.
