### ISSUE TITLE
Homepage should probably be a list of stores

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-ecommerce#24]
Think about the user story with django-ecommerce.

1. they go to the site
2. add products to bag from the list of available products (across any store)
3. checkout the order and then are required to select a store? - probably not the best user experience right?

- [ ] consider listing available stores on home page or providing a route per store /store or store.
- [ ] when the user either navigates to the store, only that store's products are displayed.

In this way, the user checkout eliminates the need for them to pick a store as you can pass the user's store to the form in code.

**Comment by kjcioffi** [comment]
Good point! An alternative I was considering was using the homepage like a product "mixin" meaning the products from all stores would populate on the same page. At checkout, there could be a way to inform users which products will be purchased from which store with the product and their quantities.

**Comment by kjcioffi** [comment]
I like the idea of pages for individual storefronts too. That way, users can view products from specific stores.
