### ISSUE TITLE
Review Overview on GitHub Actions and complete the following tasks

### ISSUE THREAD

**Issue by ryaustin** [kjcioffi/django-ecommerce#30]
https://docs.github.com/en/actions

- [x] setup a rust linter on your code on push
- [x] setup a test runner to run your unit tests on PR
- [x] Create an action to check code coverage on PR

**Comment by ryaustin** [comment]
Good job adding in some actions on PR.  Please troubleshoot and resolve the errors on the build.

**Comment by ryaustin** [comment]
Hi Kevin, will you consider an action to check code coverage during actions in this iteration?

**Comment by kjcioffi** [comment]
Hey Ryan, I’ve implemented code coverage reporting.

I’m just working out an issue with implementing linting and formatting.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
